### PR TITLE
Rebase PR: Revert WebView2 Update, Fix URL Validation (Failed Update Rollback)

### PR DESCRIPTION
**Pull request by Killerherts**
Rebased from commit b99c7ea4 on October 2, 2022.

**PR Summary:**

1. **Updated Onboarding Page for Improved URL Verification:**
   - Implemented fixes to enhance URL verification on the Onboarding page.
   
2. **Enhanced Error Handling for 3XX Status Codes:**
   - Improved error handling for 3XX status codes received during HTTPS checks.
   - Now extracts the new location from the 300 status code for redirection handling.

### CODE REVIEW

**Review by anthonylavado — APPROVED** [review]

**Comment by anthonylavado** [comment]
I'll push a fix for the conflicts, don't worry.

**Comment by anthonylavado** [comment]
So I had a look, and even asked other Git experts, and it's not easily possible to recover this PR in this state. I want you to have credit for the patch, but I don't know how I can easily apply it.

I think I'll need to make a commit to merge everything to the state you want to base off of, then you can make the necessary changes to `master`.

**Comment by Killerherts** [comment]
Ok that makes sense to me. Sorry for the extra work I wasn't sure if another way to easily proceed. After you make the commit I'll sync my recovery branch.

**Comment by Killerherts** [comment]
> Okay, we got this in. Next up is build/test/release.

I was able to test on my dev kit today everything was functioning as expected. 

One question do we have the ability to do beta releases that are private on Ms store similar to Android?
It would just be easier to get some testers for new updates.

**Pull request merged**
